export const INTERACTIVE_HIGHLIGHT_BACKGROUND = '#57A5E533';

export const INTERACTIVE_ACTIVE_HIGHLIGHT_BACKGROUND = '#00FF0033';

export const SCROLL_HIGHLIGHT_BACKGROUND = '#57A5E522';

export const SCROLL_HIGHLIGHT_BORDER = '4px solid #57A5E5FF';

export const SCROLL_HIGHLIGHT_TIMEOUT = 500;

export const SCROLL_SPEED_FAST = 500;

export const SCROLL_SPEED_SLOW = 200;

export const KEY_SEQUENCE_TIMEOUT_MS = 500;
