export const SCROLL_HIGHLIGHT_COLOR = '#57A5E5';

export const SCROLL_HIGHLIGHT_TIMEOUT = 500;

export const SCROLL_SPEED_FAST = 500;

export const SCROLL_SPEED_SLOW = 200;

export const KEY_SEQUENCE_TIMEOUT_MS = 500;
