#!/usr/bin/env bash


declare -A commands

commands=(
    [firefox]="firefox"
    [sleep]="systemctl suspend"
    [reboot]="reboot"
    [poweroff]="poweroff"
    [inkscape]="inkscape"
    [discord]="discord"
)

key=$(echo "${!commands[@]}" | tr " " "\n" | rofi -dmenu)
eval "${commands[$key]}" & disown
