#!/bin/bash

set -e

declare -A SYMLINKS=(
  ["$DOTS/.xinitrc"]="$HOME/.xinitrc"
  ["$DOTS/.zshenv"]="$HOME/.zshenv"
  ["$DOTS/awesome"]="$HOME/.config/awesome"
  ["$DOTS/nvim"]="$HOME/.config/nvim"
  ["$DOTS/flameshot"]="$HOME/.config/flameshot"
)

for SYMLINK in ${!SYMLINKS[@]}; do
  mkdir -p $(dirname ${SYMLINKS[$SYMLINK]})
  ln -sfn "$SYMLINK" ${SYMLINKS[$SYMLINK]}
done
