#!/bin/bash

set -e

declare -a LUA_VERSIONS=(
  "5.1"
  "5.2"
  "5.3"
  "5.4"
)

declare -a LUAROCKS_PACKAGES=(
  luafilesystem
  lua-cjson
  busted
  inspect
  penlight
  argparse
  readline
)

if ! [[ -d $HOME/extern/luarocks ]]; then
  mkdir -p "$HOME/extern"
  git clone git://github.com/luarocks/luarocks.git "$HOME/extern/luarocks"
fi

if ! command -v luarocks &> /dev/null; then
  cd "$HOME/extern/luarocks"
  ./configure
  make
  sudo make install
  cd -
fi

for LUA_VERSION in ${LUA_VERSIONS[@]}; do
  for PACKAGE in ${LUAROCKS_PACKAGES[@]}; do
    if ! luarocks --local --lua-version="$LUA_VERSION" show "$PACKAGE" >/dev/null 2>/dev/null; then
      luarocks --local --lua-version="$LUA_VERSION" install "$PACKAGE"
    fi
  done
done
