#!/bin/bash

set -e

declare -a PACMAN_PACKAGES=(
  # System
  # amd-ucode # AMD
  intel-ucode
  lvm2
  # upower # TODO: remove?
  # usbutils # TODO: remove?
  udiskie
  sudo

  # X11
  # xf86-video-amdgpu # AMD
  xf86-video-intel # Intel
  xorg-server
  xorg-xrandr
  # xorg-server-xephyr # TODO: remove?
  xorg-xinit
  xorg-xev # TODO: remove?
  xclip
  xsel
  awesome # TODO: remove?
  picom

  # Wifi / Bluetooth
  networkmanager
  bluez
  bluez-utils

  # Audio
  alsa-utils
  pulseaudio
  pulseaudio-alsa
  pulseaudio-bluetooth

  # Input / Fonts
  fcitx5-im
  fcitx5-mozc
  adobe-source-han-sans-jp-fonts
  ttf-hack

  # Languages
  luajit
  gcc
  clang
  bear
  nodejs
  npm

  # Tools
  reflector
  base-devel
  man-db
  man-pages
  git
  openssh
  zsh
  zip
  unzip
  ripgrep
  fd
  fzf
  brightnessctl
  htop
  pass

  # Apps
  flameshot
  gpick
  simplescreenrecorder
  neovim
  firefox-developer-edition
  arandr
)

sudo pacman -Syu --needed "${PACMAN_PACKAGES[@]}"
