#!/bin/bash

set -e

declare -a NPM_PACKAGES=(
  typescript
  typescript-language-server
  vscode-langservers-extracted
  graphql-language-service-cli
  @fsouza/prettierd
)

sudo npm i -g "${NPM_PACKAGES[@]}"
