#!/usr/bin/env bash


# ------------------------------------------------------------------------------
# - ENVIRONMENT
# - Note: this is necessary, since we haven't linked our bashrc or profile yet!
# ------------------------------------------------------------------------------

DOTS="$HOME/dots"


# -------------------------------------
# - SYMLINKS
# -------------------------------------

# X11
ln -sf "$DOTS/Xmodmap" "$HOME/.Xmodmap"
ln -sf "$DOTS/xinitrc" "$HOME/.xinitrc"

# zsh
ln -sf "$DOTS/zprofile" "$HOME/.zprofile"
ln -sf "$DOTS/zshrc" "$HOME/.zshrc"
ln -sf "$DOTS/starship.toml" "$XDG_CONFIG_HOME/starship.toml"

# awesome
ln -sfn "$DOTS/awesome" "$XDG_CONFIG_HOME/awesome"

# nvim
ln -sfn "$DOTS/nvim" "$XDG_CONFIG_HOME/nvim"

# vifm
ln -sfn "$DOTS/vifm" "$XDG_CONFIG_HOME/vifm"

# alacritty
ln -sfn "$DOTS/alacritty" "$XDG_CONFIG_HOME/alacritty"


# -------------------------------------
# - SYSTEMD UNITS
# -------------------------------------

#sudo ln -sf "$DOTS/systemd/slock.service" "/etc/systemd/system/slock.service"
#sudo systemctl enable slock.service
#sudo systemctl start slock.service
