#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# SYMBOLIC LINKS
#
# Note: Use absolute paths here, as any custom environment variables may not be
# setup yet (when installing on a new system, for example).
# ------------------------------------------------------------------------------

ln -sf "$HOME/dots/Xmodmap" "$HOME/.Xmodmap"
ln -sf "$HOME/dots/xinitrc" "$HOME/.xinitrc"

ln -sf "$HOME/dots/zsh/zprofile" "$HOME/.zprofile"
ln -sf "$HOME/dots/zsh/zshrc" "$HOME/.zshrc"

ln -sfn "$HOME/dots/awesome" "$HOME/.config/awesome"

ln -sfn "$HOME/dots/nvim" "$HOME/.config/nvim"

ln -sfn "$HOME/dots/vifm" "$HOME/.config/vifm"

ln -sf "$HOME/dots/picom.conf" "$HOME/.config/picom.conf"

sudo ln -sf "$HOME/dots/services/physlock.service" "/etc/systemd/system/physlock.service"
