#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# - ENVIRONMENT
# - Note: this is necessary if we haven't linked our zshrc or zprofile yet!
# ------------------------------------------------------------------------------

DOTS="$HOME/dots"

# -------------------------------------
# - X11
# -------------------------------------

ln -sf "$DOTS/Xmodmap" "$HOME/.Xmodmap"
ln -sf "$DOTS/xinitrc" "$HOME/.xinitrc"

# -------------------------------------
# - ZSH
# -------------------------------------

ln -sf "$DOTS/zprofile" "$HOME/.zprofile"
ln -sf "$DOTS/zshrc" "$HOME/.zshrc"

# -------------------------------------
# - SXHKD
# -------------------------------------

ln -sf "$DOTS/sxhkd" "$XDG_CONFIG_HOME/sxhkd"

# ------------------------------------------------------------------------------
# - AWESOME
# ------------------------------------------------------------------------------

# ln -sfn "$DOTS/awesome" "$XDG_CONFIG_HOME/awesome"

# ------------------------------------------------------------------------------
# - NVIM
# ------------------------------------------------------------------------------

! [[ -d "$XDG_CONFIG_HOME/nvim" ]] && mkdir "$XDG_CONFIG_HOME/nvim"
ln -sfn "$DOTS/nvim/init.vim" "$XDG_CONFIG_HOME/nvim/init.vim"
ln -sfn "$DOTS/nvim/movement.vim" "$XDG_CONFIG_HOME/nvim/movement.vim"

# ------------------------------------------------------------------------------
# - VIFM
# ------------------------------------------------------------------------------

! [[ -d "$XDG_CONFIG_HOME/vifm" ]] && mkdir "$XDG_CONFIG_HOME/vifm"
ln -sfn "$DOTS/vifm/vifmrc" "$XDG_CONFIG_HOME/vifm/vifmrc"
ln -sfn "$DOTS/vifm/colors" "$XDG_CONFIG_HOME/vifm/colors"
ln -sfn "$DOTS/vifm/scripts" "$XDG_CONFIG_HOME/vifm/scripts"

# ------------------------------------------------------------------------------
# - QUTEBROWSER
# ------------------------------------------------------------------------------

# ln -sfn "$DOTS/qutebrowser" "$XDG_CONFIG_HOME/qutebrowser"

# ------------------------------------------------------------------------------
# - ROFI
# ------------------------------------------------------------------------------

# ln -sfn "$DOTS/rofi" "$XDG_CONFIG_HOME/rofi"

# ------------------------------------------------------------------------------
# - ALACRITTY
# ------------------------------------------------------------------------------

ln -sfn "$DOTS/alacritty" "$XDG_CONFIG_HOME/alacritty"

# ------------------------------------------------------------------------------
# - MIMELIST
# ------------------------------------------------------------------------------

# ln -sf "$DOTS/mimeapps.list" "$XDG_CONFIG_HOME/mimeapps.list"

# -------------------------------------
# - SYSTEMD UNITS
# -------------------------------------

#sudo ln -sf "$DOTS/systemd/slock.service" "/etc/systemd/system/slock.service"
#sudo systemctl enable slock.service
#sudo systemctl start slock.service
