#!/usr/bin/env bash

# Change default programs. Application list can be found under:
#   /usr/share/applications
#
# Lines use the following format:
#   xdg-mime default *.desktop application/*
# ----------------------------------------

xdg-mime default feh.desktop application/png
