# ------------------------------------------------------------------------------
# ENVIRONMENT
# ------------------------------------------------------------------------------

export SHELL="/bin/zsh"
export EDITOR=nvim

export XDG_CONFIG_HOME="$HOME/.config"
export DOTS="$HOME/dots"
export AWESOME="$DOTS/awesome"
export QUTEBROWSER="$DOTS/qutebrowser"
export NVIM="$DOTS/nvim"
export VIFM="$DOTS/vifm"
export ZSH="$DOTS/zsh"

export HISTFILE=~/.histfile
export HISTSIZE=1000
export SAVEHIST=1000

export LC_ALL=en_US.UTF-8

export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT5_IM_MODULE=fcitx
export QT_QPA_PLATFORMTHEME=qt5ct

# ------------------------------------------------------------------------------
# SPACESHIP-PROMPT
# ------------------------------------------------------------------------------

export SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  node          # Node.js section
  pyenv         # Python
  venv          # Python venv
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# ------------------------------------------------------------------------------
# FZF
# ------------------------------------------------------------------------------

export FZF_DEFAULT_COMMAND='rg --files'
export FZF_DEFAULT_OPTS='--exact'

# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------

if [[ -f $ZSH/__config/zprofile ]]; then
	source $ZSH/__config/zprofile
fi

# ------------------------------------------------------------------------------
# STARTUP
# ------------------------------------------------------------------------------

# run startx on login
if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi

# vim: syntax=zsh
